image: node:latest

#tests:
#  stage: tests
#  script:
#    - echo 'Tests passed!'

production:
  stage: build
  script:
    - npm i --progress=false
    - npm run 'to production'
  artifacts:
    paths:
      - public
