image: node:latest

#cache:
#  paths:
#  - node_modules/

#tests:
#  stage: tests
#  script:
#    - echo 'Tests passed!'

pages:
  stage: deploy
  script:
    - npm i --progress=false
    - npm run 'to production'
  artifacts:
#    name: 'pages'
#    expire_in: 1 week
    paths:
      - public
