image: node:latest

before_script:
  - npm i

cache:
  paths:
    - node_modules/

stages:
  - lint
  - test
  - build
  - deploy


# Lint
eslint:
  stage: lint
  script:
    - npm run lint
    - echo 'Lint passed!'


# Test
unit tests:
  stage: test
  script:
    # TODO: Add tests
    - echo 'Tests are passed!'


# Build
webpack:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist

jsdoc:
  stage: build
  script:
    # Run jsdoc with config
    - npm run docs
  artifacts:
    paths:
      - dev


# Deploy
pages:
  stage: deploy
  script:
    - mkdir public
    # Dashboard
    - mv dist/* public
    # Documentation folder
    - mv dev public
    # Compress to gzip
    - find public \( -name '*.html' -o -name '*.css' -o -name '*.js' \) -print0 | xargs -0 gzip -9 -kv
  artifacts:
    paths:
      - public
  only:
    - master

npm:
  stage: deploy
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish
