image: node:latest

before_script:
  - npm i

cache:
  paths:
    - node_modules/

webpack:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - echo 'Tests are passed!'

pages:
  stage: deploy
  script:
    - mv -v dist/* public/
  artifacts:
    paths:
      - public
  only:
    - master
