image: node:latest

before_script:
  - npm i

cache:
  paths:
    - node_modules/

stages:
  - lint
  - test
  - build
  - docs
  - deploy


# Lint
eslint:
  stage: lint
  script:
    - npm run lint
    - echo 'Lint passed!'


# Test
unit tests:
  stage: test
  script:
    - echo 'Tests are passed!'


# Build
webpack:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist


# Docs
jsdoc:
  stage: docs
  script:
    # Run jsdoc with config
    - npm run docs
  artifacts:
    paths:
      - dev


# Deploy
pages:
  stage: deploy
  script:
    - mkdir public
    # Dashboard
    - mv dist/* public
    # Documentation folder
    - mv dev public
  artifacts:
    paths:
      - public
  only:
    - master
