image: node:latest

before_script:
  - npm i

cache:
  paths:
    - node_modules/

docs:
  stage: build
  script:
    # Run jsdoc with config
    - npm run docs
  artifacts:
    paths:
      - docs

webpack:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist

test:
  stage: test
  script:
    # TODO: tests
    - echo 'Tests are passed!'

pages:
  stage: deploy
  script:
    - mkdir public
    # Dashboard
    - mv dist/* public
    # Documentation folder
    - mv docs public
    # Rename it for /dev/ path
    - mv public/docs public/dev
  artifacts:
    paths:
      - public
  only:
    - master
