image: node:latest

before_script:
  - npm i

cache:
  paths:
    - node_modules/


lint:
  stage: test
  script:
    - npm run lint

unit-tests:
  stage: test
  script:
    # TODO: tests
    - echo 'Tests are passed!'


webpack:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist


docs:
  stage: deploy
  script:
    # Run jsdoc with config
    - npm run docs
  artifacts:
    paths:
      - dev

pages:
  stage: deploy
  script:
    - mkdir public
    # Dashboard
    - mv dist/* public
    # Documentation folder
    - mv dev public
  artifacts:
    paths:
      - public
  only:
    - master
