image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm i --progress=false

pages:
  stage: deploy
  script:
    - npm run 'to production'
  artifacts:
    paths:
    - public
  only:
  - master

test:
  stage: test
  script:
  - echo "Tests are passed!"
#  artifacts:
#    paths:
#    - test
#  except:
#  - master
