// Imports
// CSS
import '../css/dashboard.css';
import '../css/default.css';
import '../css/preloader.css';
import '../css/promotion.css';
import '../css/switcher.css';
// JS
import './lib/backupRestore';
import './lib/candidates';
import './lib/promotion';
import './lib/settings';
import './lib/socketDonationAlerts';
import './lib/timer';
import './lib/colorPicker';
